# Page settings
baseurl = "/"
title = "Rapoo- It solutions &amp; Corporate template"
languageCode = "en-us"
theme = "hugo-elate-rappo"

[params]

  # Meta
  author = ""
  description = ""
  email = ""

  # Navigation
  [params.navigation]
    brand = "Rappo"
    home = "Home"
    about = "About"
    services = "Services"
    pricing = "Pricing"
    projects = "Projects"
    contact = "Contact"

  # Hero section
  [params.hero]
    title = "Industry Leading Managed Services Solutions"
    subtitle = "Pindom is set of landing and support pages aimed at helping companies promote new products and business launches."
    button = "Purchase now"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

  # Services section
  [params.services]
    enable = false
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

  # Pricing section
  [params.pricing]
    enable = false
    title = "Pricing"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

  # Contact section
  [params.contact]
    enable = false
    title = "Contact"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

  # Features section
  [params.features]

  [[params.features.item]]
    title = "The right advice"
    description = "We've been awarded for our high rate of customer satisfaction."
    icon = "ti-thumb-up"

  [[params.features.item]]
    title = "Recognised for excellence"
    description = "We've been awarded for our high rate of customer satisfaction."
    icon = "ti-cup"

  [[params.features.item]]
    title = "Compare the best"
    description = "We only compare market leaders with a reputation for service quality."
    icon = "ti-wallet"

  [[params.features.item]]
    title = "Premium Services"
    description = "We only compare market leaders with a reputation for service quality."
    icon = "ti-dashboard"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Copyright <span class="current-year"><a href="https://themefisher.com/free-bootstrap-templates">Free Bootstrap Templates</a></span> All rights reserved.'
    links = [
        ["#", "fab fa-facebook-f", "Facebook"],
        ["#", "fab fa-twitter", "Twitter"],
        ["#", "fab fa-pinterest-p", "Pinterest"],
        ["#", "fab fa-linkedin", "linkedin"],
        ["#", "fab fa-youtube", "YouTube"]
      ]

